# Use postgres/example user/password credentials
version: '3.5'

services:
  postgres:
    container_name: postgres_container
    build: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
      PGDATA: ${PGDATA:-/data/postgres}
    volumes:
      - postgres:${PGDATA:-/data/postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - nest_app
    restart: unless-stopped
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_server
    environment:
      DB_HOST: ${PORT:-postgres_container}
      DB_PORT: ${DB_PORT:-5432}:5432}
      DB_USERNAME: ${DB_USERNAME:-'postgres'}
      DB_PASSWORD: ${DB_PASSWORD:-'123456'}
      DB_NAME: ${DB_NAME:-'postgres'}
    depends_on:
      - postgres
    ports:
      - '3030:3030'
    networks:
      - nest_app
    volumes:
      - ./src:/app/src

networks:
  nest_app:
    driver: bridge

volumes:
  postgres: