# Use postgres/example user/password credentials
version: '3.5'

services:
  postgres:
    container_name: postgres_container
    build: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
      PGDATA: ${PGDATA:-/data/postgres}
    volumes:
      - postgres:${PGDATA:-/data/postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - postgres
    restart: unless-stopped
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_server
    environment:
      - PORT=${PORT}
    ports:
      - '3030:3030'
    volumes:
      - ./src:/app/src

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
